//
// Generated file, do not edit! Created by opp_msgtool 6.2 from messages/DataPacket.msg.
//

#ifndef __DATAPACKET_M_H
#define __DATAPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DataPacket;
/**
 * Class generated from <tt>messages/DataPacket.msg:16</tt> by opp_msgtool.
 * <pre>
 * message DataPacket
 * {
 *     string sourceIP;
 *     string destIP;
 *     string payload;
 *     int packetId;
 * }
 * </pre>
 */
class DataPacket : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string sourceIP;
    omnetpp::opp_string destIP;
    omnetpp::opp_string payload;
    int packetId = 0;

  private:
    void copy(const DataPacket& other);

  protected:
    bool operator==(const DataPacket&) = delete;

  public:
    DataPacket(const char *name=nullptr, short kind=0);
    DataPacket(const DataPacket& other);
    virtual ~DataPacket();
    DataPacket& operator=(const DataPacket& other);
    virtual DataPacket *dup() const override {return new DataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSourceIP() const;
    virtual void setSourceIP(const char * sourceIP);

    virtual const char * getDestIP() const;
    virtual void setDestIP(const char * destIP);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual int getPacketId() const;
    virtual void setPacketId(int packetId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DataPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DataPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<DataPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DATAPACKET_M_H

