//
// Generated file, do not edit! Created by opp_msgtool 6.2 from messages/DhcpMessage.msg.
//

#ifndef __DHCPMESSAGE_M_H
#define __DHCPMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DhcpMessage;
/**
 * Class generated from <tt>messages/DhcpMessage.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message DhcpMessage
 * {
 *     string type; // DISCOVER, OFFER, REQUEST, ACK
 *     int clientId;
 *     int proposedAddress = -1;
 * }
 * </pre>
 */
class DhcpMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string type;
    int clientId = 0;
    int proposedAddress = -1;

  private:
    void copy(const DhcpMessage& other);

  protected:
    bool operator==(const DhcpMessage&) = delete;

  public:
    DhcpMessage(const char *name=nullptr, short kind=0);
    DhcpMessage(const DhcpMessage& other);
    virtual ~DhcpMessage();
    DhcpMessage& operator=(const DhcpMessage& other);
    virtual DhcpMessage *dup() const override {return new DhcpMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getType() const;
    virtual void setType(const char * type);

    virtual int getClientId() const;
    virtual void setClientId(int clientId);

    virtual int getProposedAddress() const;
    virtual void setProposedAddress(int proposedAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DhcpMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DhcpMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DhcpMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<DhcpMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DHCPMESSAGE_M_H

