//
// Generated file, do not edit! Created by opp_msgtool 6.2 from messages/DnsMessage.msg.
//

#ifndef __DNSMESSAGE_M_H
#define __DNSMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DnsMessage;
/**
 * Class generated from <tt>messages/DnsMessage.msg:16</tt> by opp_msgtool.
 * <pre>
 * message DnsMessage
 * {
 *     string type; // QUERY, RESPONSE
 *     string domainName;
 *     string ipAddress;
 *     int queryId;
 * }
 * </pre>
 */
class DnsMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string type;
    omnetpp::opp_string domainName;
    omnetpp::opp_string ipAddress;
    int queryId = 0;

  private:
    void copy(const DnsMessage& other);

  protected:
    bool operator==(const DnsMessage&) = delete;

  public:
    DnsMessage(const char *name=nullptr, short kind=0);
    DnsMessage(const DnsMessage& other);
    virtual ~DnsMessage();
    DnsMessage& operator=(const DnsMessage& other);
    virtual DnsMessage *dup() const override {return new DnsMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getType() const;
    virtual void setType(const char * type);

    virtual const char * getDomainName() const;
    virtual void setDomainName(const char * domainName);

    virtual const char * getIpAddress() const;
    virtual void setIpAddress(const char * ipAddress);

    virtual int getQueryId() const;
    virtual void setQueryId(int queryId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DnsMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DnsMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DnsMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<DnsMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DNSMESSAGE_M_H

